#!/bin/sh

mathjax_newcommands=()

gen_mathjax_newcommands() {
	IFS=',' read -ra string <<< $line

	macro=
	shortcut=${string[1]}
	macro+="${shortcut}: [\""

	command=${string[3]}
	num=${#string[@]}
	if [[ $num -gt 4 ]]; then
		for i in $(seq 4 $((num - 1))); do
			command+=",${string[$i]}"
		done
	fi
	command=$(echo ${command} | sed 's/\\/\\\\/g')
	macro+="${command}\","

	number=${string[2]}
	macro+="${number}],"

	mathjax_newcommands+=("$macro")
}

num_macros=0
while read -r line; do 
	if [[ ${line:0:2} == "nc" || ${line:0:2} == "rn" ]]; then
		gen_mathjax_newcommands $line
		num_macros=$((num_macros + 1))
	fi
done < newcommands

touch commandlist.html
cat head.html | head -n 4 > commandlist.html

for i in $(seq 1 $num_macros); do
	printf '\t\t\t\t%s\n' "${mathjax_newcommands[i]}" >> commandlist.html
done

cat tail.html | tail -n 25 >> commandlist.html
mv commandlist.html ../config/newcommands.html
